apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: kubernetes-alerts
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:
  - name: test.rules
    rules:

    - alert: AlwaysFiringTest
      expr: vector(1)
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Test alert always firing"
