apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: demo-app
  namespaceSelector:
    any: true
  endpoints:
  - port: http
    path: /
    interval: 15s
